const cardData = [
  {
    value: 2,
    displayValue: "2",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 3,
    displayValue: "3",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 4,
    displayValue: "4",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 5,
    displayValue: "5",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 6,
    displayValue: "6",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 7,
    displayValue: "7",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 8,
    displayValue: "8",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 9,
    displayValue: "9",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 10,
    displayValue: "10",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 11,
    displayValue: "J",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 12,
    displayValue: "Q",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 13,
    displayValue: "K",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 14,
    displayValue: "A",
    suit: "♥",
    suitColor: "Red",
  },
  {
    value: 2,
    displayValue: "2",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 3,
    displayValue: "3",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 4,
    displayValue: "4",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 5,
    displayValue: "5",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 6,
    displayValue: "6",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 7,
    displayValue: "7",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 8,
    displayValue: "8",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 9,
    displayValue: "9",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 10,
    displayValue: "10",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 11,
    displayValue: "J",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 12,
    displayValue: "Q",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 13,
    displayValue: "K",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 14,
    displayValue: "A",
    suit: "♦",
    suitColor: "Red",
  },
  {
    value: 2,
    displayValue: "2",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 3,
    displayValue: "3",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 4,
    displayValue: "4",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 5,
    displayValue: "5",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 6,
    displayValue: "6",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 7,
    displayValue: "7",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 8,
    displayValue: "8",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 9,
    displayValue: "9",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 10,
    displayValue: "10",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 11,
    displayValue: "J",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 12,
    displayValue: "Q",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 13,
    displayValue: "K",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 14,
    displayValue: "A",
    suit: "♠",
    suitColor: "Black",
  },
  {
    value: 2,
    displayValue: "2",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 3,
    displayValue: "3",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 4,
    displayValue: "4",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 5,
    displayValue: "5",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 6,
    displayValue: "6",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 7,
    displayValue: "7",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 8,
    displayValue: "8",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 9,
    displayValue: "9",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 10,
    displayValue: "10",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 11,
    displayValue: "J",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 12,
    displayValue: "Q",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 13,
    displayValue: "K",
    suit: "♣",
    suitColor: "Black",
  },
  {
    value: 14,
    displayValue: "A",
    suit: "♣",
    suitColor: "Black",
  }
];
